language: android
jdk: oraclejdk8
sudo: false

env:
    matrix:
        - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=15    #Time out to 10 minsx

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
      - $HOME/.gradle/caches/
      - $HOME/.gradle/daemon
      - $HOME/.gradle/native
      - $HOME/.gradle/wrapper     #Cache the gradle

android:
#    update_sdk: true
    components:
        - tools
        - build-tools-26.0.0
        - platform-tools
        - android-22
        - android-26

        # Additional components
        - extra-google-m2repository
        - extra-android-m2repository
        - extra-google-android-support

        #system images
        - sys-img-armeabi-v7a-android-22

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
    - android list targets
    - chmod +x gradlew      #Grand permissions
    - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator


script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull rekquest $TRAVIS_PULL+REQUEST"
    - ./gradlew test
    - ./gradlew test
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest
